const Routes={
    Login:'Login',
    Register:'Register',
    Authenticate:'Authenticate',
    NotAuthenticate:'NotAuthenticate',
    SplashScreen:'SplashScreen',
    Home:'Home',
    HomeDetail:'HomeDetail',
    UserProfile:'UserProfile',
    Auth:'Auth',
    Setting:'Setting',
    Bottomtab:'Bottomtab',
    DrawerScreen:'DrawerScreen',
    GiphyScreen:'GiphyScreen',
    TabBar:'TabBar',
    SwipeCard:'SwipeCard',
    Increment:'Increment',
    Decrement:'Decrement',
    IncrementDecrement:'IncrementDecrement',
    ToDo:'ToDo',
    Quote:'Quote',
    Contact:'Contact',
}

export default Routes;